# +-------------------------------------------------------------------------+ #
# |                     ╔╗ ┬ ┬┌┬┐┌─┐  ╔╦╗┌─┐┌─┐┌─┐                          | #
# |                     ╠╩╗└┬┘ │ ├┤    ║ ├─┤│ ┬└─┐                          | #
# |                     ╚═╝ ┴  ┴ └─┘   ╩ ┴ ┴└─┘└─┘                          | #
# |                                                                         | #
# |                         Made By Alex Infanti                            | #
# |                            play.sodemc.com                              | #
# |                                                                         | #
# |                       --------------------------                        | #
# |                                                                         | #
# |                              CONFIG FILE                                | #
# |                                                                         | #
# |              Here, you can edit all the properties of ByteTags.         | #
# |                                                                         | #
# +-------------------------------------------------------------------------+ #

Tags:
  Rich:
    Material: 'OAK_PLANKS'
    Name: 'Oak One'
  Best:
    Material: 'STONE'
    Name: 'Stone One'